Add support for multiple player markers
mspielberg/dv-remote-dispatch pull request #7
Opened 2023-03-11 07:40 UTC by Insprill

Adds support for displaying multiple player markers. This allows the multiplayer mod to patch the PlayerData functions and display markers for all players.

I'm not much of a JS developer so if there's a better way to do any of the frontend changes please let me know!

2023-03-18 01:00 UTC, mspielberg requested changes

2023-03-18 01:00 UTC, mspielberg commented on main.js
> +  map.setView(playerMarkers.values().next().value.getBounds().getCenter(), initialZoom);
`next()` isn't really intended for direct use; it's mostly support for `for` iteration. I would suggest doing a lookup for the `player` key to support the single-player usecase, and simply do nothing if `player` is not present.

2023-03-18 01:00 UTC, mspielberg commented on main.js
> +  let existingPlayerIds = Array.from(playerMarkers.keys());
Use `const` for any local variable you don't intend to modify.

2023-03-18 01:00 UTC, mspielberg commented on PlayerData.cs
> +            return new JObject(new JProperty("players", new JArray(new JObject(
I would suggest returning a JObject keyed by player id, rather than using an array.

2023-03-18 01:00 UTC, mspielberg commented on main.js
> +  .filter(id => !data.players.some(player => player.id === id))
Using a JSON object for players would avoid needing to do this O(n^2) searching.

2023-03-18 01:00 UTC, mspielberg commented on main.js
> +  svg.innerHTML = `<polygon id="playerPolygon-${playerData.id}" fill="${playerData.color}" fill-opacity="70%" stroke="black" stroke-width="1%" points="0,-10 10,10 0,5 -10,10"/>`;
This is vulnerable to an injection attack, since players pick their own `id`s, and it could contain a double quote to escape from the string context. You'll need to not use `innerHTML`, and instead use `document.createElement`, `setAttribute()`, etc. to build up the SVG.

2023-03-18 01:00 UTC, mspielberg commented on main.js
> +  map.setView(data.players[0].position, initialZoom);
As above, I'd suggest trying to find `player` for single-player, and if not present, just leave the map at the initial view to show the whole map.

2023-03-18 01:03 UTC, Insprill commented on main.js
> +  svg.innerHTML = `<polygon id="playerPolygon-${playerData.id}" fill="${playerData.color}" fill-opacity="70%" stroke="black" stroke-width="1%" points="0,-10 10,10 0,5 -10,10"/>`;
Player IDs are a ushort assigned by the server to uniquely identify a connection, I can still make this change though.

2023-03-18 01:18 UTC, Insprill commented on main.js
> +  map.setView(playerMarkers.values().next().value.getBounds().getCenter(), initialZoom);
The current behavior will zoom into the host of a multiplayer session. Perhaps instead it could zoom in just enough to show all players?

2023-03-29 19:31 UTC, mspielberg approved these changes

2023-03-29 19:31 UTC, merged